image:
  registry: augury.azurecr.io
  tag: master
  pullPolicy: IfNotPresent
envVars:
  azureDeployment: gpt-4o
  openaiModelVersion: 2023-03-15-preview
  langchainTracing: "true"
nodeSelector:
  data-micrsoservices-node: 'true'
tolerations:
- key: data-micrsoservices-node
  operator: Equal
  value: 'true'
  effect: NoSchedule
- key: kubernetes.azure.com/scalesetpriority
  operator: Equal
  value: spot
  effect: NoSchedule
api:
  replicaCount: 2
  resources:
     limits:
       cpu: 60m
       memory: 100Mi
     requests:
       cpu: 50m
       memory: 100Mi
       
async:
  replicaCount: 0
  hpa:
    minReplicas: 4
    maxReplicas: 100
    targetCpuAverage: 85
    enabled: true
  resources:
    limits:
      cpu: 110m
      memory: 375Mi
    requests:
      cpu: 100m
      memory: 350Mi
